cargo-features = ["codegen-backend"]

[package]
name = "wgpu-experiments"
version = "0.1.0"
edition = "2021"

[profile.dev]
codegen-backend = "cranelift"

[dependencies]
winit = "0.29"
env_logger = "0.11"
log = "0.4"
wgpu = "0.19"
futures = "0.3"
